---

- name: Get Devmaster root
  shell: |
    {{ drush_bin_path }} @hostmaster status --fields="root" --field-labels=0 2>/dev/null | tr "\n" " " | sed -e "s/^[[:space:]]*//g" -e "s/[[:space:]]*\$//g"
  become: true
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  ignore_errors: true
  register: devmaster_site_root
  changed_when: "devmaster_site_root.stdout != empty_string"
  tags: [install-devmaster]

- name: Get Devmaster URI
  shell: |
    {{ drush_bin_path }} @hostmaster status --fields="uri" --field-labels=0 2>/dev/null | tr "\n" " " | sed -e "s/^[[:space:]]*//g" -e "s/[[:space:]]*\$//g"
  become: true
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  ignore_errors: true
  register: devmaster_site_uri
  changed_when: "devmaster_site_uri.stdout != empty_string"
  tags: [install-devmaster]

- name: Set devmaster_site_root and devmaster_site_uri variables
  set_fact:
    devmaster_site_root: "{{ devmaster_site_root.stdout }}"
    devmaster_site_uri: "{{ devmaster_site_uri.stdout }}"
  tags: [install-devmaster]

- name: Devmaster Root
  debug:
    msg: "{{ devmaster_site_root }}"
  tags: [install-devmaster]

- name: Devmaster URI
  debug:
    msg: "{{ devmaster_site_uri }}"
  tags: [install-devmaster]

- name: Devmaster Install Command
  debug:
    msg: "{{ devmaster_install_command }}"
  tags: [install-devmaster]

- name: Wait for MySQL Server to be ready.
  command: "{{ devshop_cli_bin_path }}/mysql-wait"
  changed_when: true
  tags: [install-devmaster]

- name: Install Devmaster
  become: true
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  command: "{{ devmaster_install_command }}"
  when:
    - devmaster_site_uri == empty_string
  tags: [install-devmaster]

- name: Devmaster Upgrade Command
  debug:
    msg: "{{ devmaster_upgrade_command }}"
  tags: [install-devmaster]

- name: "Upgrade Devmaster to {{ devshop_version }}"
  command: "{{ devmaster_upgrade_command }}"
  when:
    - devmaster_site_uri != empty_string
    - not devmaster_skip_upgrade
  tags: [install-devmaster]

- name: Clear the drush cache.
  command: "{{ drush_bin_path }} cc drush"
  become: true
  become_user: "{{ aegir_user_name }}"
  become_method: "{{ ansible_become_method_aegir }}"
  register: drush_cache_clear
  changed_when: "drush_cache_clear.stdout != empty_string"
  tags: [install-devmaster]

- name: restart supervisor
  debug:
  tags: [install-devmaster]
  when: supervisor_started
  notify: restart supervisor
